@startwbs
+ Оранжевая книга

++ Степень доверия
+++ Политика безопасности
+++ Уровень гарантированости

++ Монитор обращений, ядро безовасности
+++ Изолированность
+++ Полнота
+++ Верифицируемость

++ Механизмы безопасности
+++ Произвольное управление доступом
+++ Безопасность повторного использованиия объектов
+++ Метки безопасноти
++++ Уровень секретности
++++ Список категорий
+++ Принудительное управление доступом

++ Принудительное (или мандатное) управление
+++ Идентификация и антентификация
+++ Предоставление доверенного пути
+++ Анализ регистрационной информации

++ Пасивные методы защиты
+++ Операционная гарантированость
++++ Архитектура системы
++++ Целостность системы
++++ Проверка тайных каналов передачи информации
++++ Доверенное администрирование
++++ Доверенное восстановление после сбоев
+++ Технологическая гарантированность
++++ Период проектирования
++++ Период реализации
++++ Период тестирования
++++ Период продажи
++++ Период сопровождения

++ Классы безопасности
+++ С1
+++ С2
+++ В1
+++ В2
+++ В3
+++ А1
@endwbs