@startwbs
+ Стандарт ISO/IEC 15408 "Критерии оценки безопасности информационных технологий"

++ Виды требования безопасности
+++ Функциональные
+++ Требования доверия

++ Этапы жизненного цикла объекта
+++ Определение назначения, условий применения, целей применения, целей и требований безопасности
+++ Проектирование и разработка
+++ Испытания, оценка и сертификация

++ Условия и урозы
+++ Источник урозы
+++ Метод воздействия
+++ Уязвимые места, которые могут быть использованны, могут возникнуть из-за недостатка в:
++++ Требованиях безопасности
++++ Проектировании
++++ Эксплуатации
+++ Ресурсы(активны), которые могут пострадать

++ Иерархия пространства требований
+++ Классы
+++ Семейства
+++ Компонент
+++ Элемент

++ Функциональные требования
+++ Идентификация и аунтентификация
+++ Защита данных пользователя
+++ Защита финкций безопасности
+++ Управления функций безопасности
+++ Управление безопасностью
+++ Аудит безопасности
+++ Доступ к объекту оценки
+++ Приватность
++++ Анонимность
++++ Псевдонимность
++++ Невозможность асоциации
++++ Скрытность
+++ Использование ресурсов
++++ Отказоустойчивость
++++ Обслуживание по приоритета
++++  Распреление ресурсов
+++ Криптографическая поддержка
+++ Связь
+++ Доверенный маршрут/канал

++ Требования доверия безопасности
+++ Разработка
+++ Подержка жизненного цикла
+++ Тестирование
+++ Оценка уязвимостей
+++ Поставка и эксплуатация
+++ Управление конфигурацией
+++ Руководства
+++ Поддержка доверия
+++ Оценка профиля защиты
+++ Оценка задания по безопасности
@endwbs