@startwbs
+ Информационная безопасность распределенных систем. Рекомендации X.800

++ Сервисы безопасности
+++ Аунтентификация
+++ Управление доступом
+++ Конфинденциальность данных
+++ Целостность данных
+++ Неотказуемость

++ Реализация сервисов(функций) безопасности
+++ Шифрование
+++ Электронная цифровая подпись
+++ Механизмы управления доступом
+++ Механизмы контроля цлостновсти данных
+++ Механизмы аутентификации
+++ Механизмы дополнения трафика
+++ Механизмы управления маршрутизацией
+++ Механизмы нотаризации

++ Администрирование средств безопасности
+++ Администрирование информационной системы в целом
+++ Администрирование сервисов безопасности
++++ Опеределение защищаемых объектов
++++ Выработку правил подбора механизмов безопасности(при наличии альтернатив)
++++ Комбинирование механизмов для реализации сервисов
++++ Взаимодействие с другими администраторами для обеспечения согласованное работы
+++ Администрирование механизмов безопасности
++++ Управление ключами(генерация и распределение)
++++ Управление шифрованием(установка и синхронизация кривтографических параметров)
++++ Администрирование управления доступом
++++ Управления аутентификацией
++++ Управление дополнением трафика
++++ Управление маршрутизацией
++++ Управление нотаризацией
@endwbs