@startwbs
+ Гармонизированные критерии Европейских стран

++ Система
++ Продукт

++ Требования к обеспечению безопасности
+++ Идентификация
+++ Аутентификация
+++ Управление доступом или восстановление после сбоев

++ Гарантированность
+++ Эффективность
++++ Мощность базовая
++++ Мощность средняя
++++ Мощность высокая
+++ Корректность
++++ Е0
++++ Е1
++++ Е2
++++ Е3
++++ Е4
++++ Е5
++++ Е6
@endwbs